"""init

Revision ID: 7d3159285a2d
Revises: 
Create Date: 2026-08-24 09:26:14.338620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d3159285a2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('action_event', sa.String(), nullable=False),
    sa.Column('delay_time', sa.Integer(), nullable=False),
    sa.Column('delay_unit', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('subject_line', sa.String(), nullable=False),
    sa.Column('message_body', sa.String(), nullable=False),
    sa.Column('cta_text', sa.String(), nullable=False),
    sa.Column('cta_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('target_audience', sa.String(), nullable=False),
    sa.Column('last_triggered', sa.String(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('initials', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('last_service', sa.String(), nullable=False),
    sa.Column('last_service_date', sa.String(), nullable=False),
    sa.Column('raw_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('suggested_upsell', sa.String(), nullable=False),
    sa.Column('preferred_channel', sa.String(), nullable=False),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False),
    sa.Column('avatar_bg', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('timeline_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date_group', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('target_client', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['automation_campaigns.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('clients')
    op.drop_table('automation_campaigns')
    # ### end Alembic commands ###
